name: UHCRun
main: net.samagames.uhcrun.UHCRun
version: 2.0
depend: [WorldEdit]
softdepend: [SamaGamesAPI]
load: STARTUP
commands:
   nextevent:
      description: Execute le prochain evenement de force
      usage: /<command>
      permission: sg.op
      permission-message: Permission non accordée